language: python
python: "2.7"

dist: xenial

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
    - zinaida:cS9FF04mRHHE6y1jGXXbpxRy#builds

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install --upgrade pip
  - pip install ansible
  - ansible --version
  - pip install ansible-lint
  - ansible-lint --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
 - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
 - ansible-lint tests/test.yml
